# Xbox-style controller controls for Super Kazeta DVD Movie.
GAMEPAD_ACTION_DOWN cycle pause
GAMEPAD_ACTION_RIGHT quit
GAMEPAD_ACTION_LEFT cycle audio
GAMEPAD_ACTION_UP cycle sub
GAMEPAD_START cycle pause
GAMEPAD_BACK quit
GAMEPAD_DPAD_LEFT seek -10
GAMEPAD_DPAD_RIGHT seek 10
GAMEPAD_DPAD_UP add chapter 1
GAMEPAD_DPAD_DOWN add chapter -1
GAMEPAD_LEFT_SHOULDER add chapter -1
GAMEPAD_RIGHT_SHOULDER add chapter 1
GAMEPAD_LEFT_TRIGGER seek -60
GAMEPAD_RIGHT_TRIGGER seek 60

ENTER cycle pause
ESC quit
LEFT seek -10
RIGHT seek 10
UP add chapter 1
DOWN add chapter -1
