listen=YES
listen_ipv6=NO
listen_port=2121
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=002
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=NO
syslog_enable=YES
connect_from_port_20=NO
chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/var/kazeta/ftp
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009
pam_service_name=vsftpd
secure_chroot_dir=/usr/share/empty
