author = "PixelGriff Studios"
description = "Live ProjectM visuals driven by a shuffled PlayFusion music library."
menu_position = "Center"
profile_badge_position = "RIGHT"
font_color = "PLAYFUSION"
cursor_color = "PLAYFUSION"
cursor_style = "BOX"
cursor_blink_speed = "NORMAL"
cursor_transition_speed = "FAST"
background_scroll_speed = "OFF"
color_shift_speed = "OFF"
bgm_track = "MP3 PLAYER"
logo_selection = "PlayFusion (Default)"
background_selection = "ProjectM Fusion"
font_selection = "Default"
sfx_pack = "Default"
